import { useCallback, useEffect, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, MenuItem, Stack, Switch, TextField, Typography } from '@mui/material'
import { apiClient } from '../../services/api'
import { groupService } from '../../services/group'
import type { Group } from '../../types'
import { getErrorMessage } from '../../utils/errorMessage'

interface Link { id: number; link_id: string; local_center_id: string; remote_center_id: string; local_group_id: number; remote_group_id: number; enabled: boolean; accepted: boolean; virtual_device_name: string; local_send_audio?: boolean; local_receive_audio?: boolean }
interface Peer { link: Link; runtime: { online: boolean; in_packets?: number; out_packets?: number; dropped_packets?: number; last_error?: string } }
interface Response<T> { code: number; message?: string; data: T }
interface LinkData { items: Peer[]; center_id: string; runtime_enabled: boolean }

export function InterCenterLinksPage() {
 const [data, setData] = useState<LinkData>({ items: [], center_id: '', runtime_enabled: false }); const [groups, setGroups] = useState<Group[]>([])
 const [inviteOpen, setInviteOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [generated, setGenerated] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
 const [invite, setInvite] = useState({ local_group_id: 0, send_audio: true, receive_audio: true, virtual_device_name: '' }); const [incoming, setIncoming] = useState({ invite_token: '', remote_address: '', local_group_id: 0, send_audio: true, receive_audio: true })
 const load = useCallback(async () => { try { const res = await apiClient.get<Response<LinkData>>('/api/inter-center-links'); setData(res.data); setError('') } catch (e) { setError(getErrorMessage(e, '读取中心互联失败')) } }, [])
 useEffect(() => { void load(); const t = setInterval(() => { if (!document.hidden) void load() }, 5000); return () => clearInterval(t) }, [load])
 useEffect(() => { void groupService.listAll({ admin: true }).then(gs => setGroups(gs.filter(g => g.status === 1 && !g.is_virtual))).catch(e => setError(getErrorMessage(e, '读取群组失败'))) }, [])
 const submitInvite = async () => { setBusy(true); setError(''); try { const res = await apiClient.post<Response<{ invite_token: string }>>('/api/inter-center-links/invites', invite); setInviteOpen(false); setGenerated(res.data.invite_token); await load() } catch (e) { setError(getErrorMessage(e, '生成邀请失败')) } finally { setBusy(false) } }
 const submitImport = async () => { setBusy(true); setError(''); try { await apiClient.post('/api/inter-center-links/import', incoming); setImportOpen(false); setIncoming({ invite_token: '', remote_address: '', local_group_id: 0, send_audio: true, receive_audio: true }); await load() } catch (e) { setError(getErrorMessage(e, '导入邀请失败')) } finally { setBusy(false) } }
 return <Stack spacing={3} sx={{ minWidth: 0 }}>
  <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} justifyContent="space-between"><Box><Typography variant="h5" fontWeight={700}>中心互联</Typography><Typography color="text.secondary">通过邀请 Token 建立中心互联，音频使用主 UDP 通道。</Typography></Box><Stack direction="row" spacing={1}><Button onClick={() => void load()}>刷新</Button><Button variant="outlined" onClick={() => setImportOpen(true)}>导入对端邀请</Button><Button variant="contained" onClick={() => setInviteOpen(true)}>生成邀请</Button></Stack></Stack>
  {error && <Alert severity="error">{error}</Alert>}{!data.runtime_enabled && <Alert severity="warning">中心互联服务未开启。启用 Interconnect.Enabled 后重启主站。</Alert>}
  <Card variant="outlined"><CardContent><Typography fontWeight={600}>本地中心：{data.center_id || '未配置'}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>远端音频将以虚拟服务器设备显示在本地群组中。</Typography></CardContent></Card>
  {data.items.length === 0 && <Alert severity="info">尚未建立中心互联。可以先生成邀请并将 Token 交给对端。</Alert>}
  <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: 'repeat(2, minmax(0, 1fr))' }, gap: 2 }}>{data.items.map(({ link: l, runtime: r }) => <Card variant="outlined" key={l.id}><CardContent><Stack direction="row" justifyContent="space-between" spacing={1}><Typography fontWeight={700} sx={{ overflowWrap: 'anywhere' }}>{l.link_id}</Typography><Chip size="small" label={r.online ? '在线' : l.enabled && l.accepted ? '等待 UDP' : '已停用'} color={r.online ? 'success' : 'default'} /></Stack><Typography sx={{ mt: 2 }}>{l.local_center_id} 群组 {l.local_group_id} ↔ {l.remote_center_id} 群组 {l.remote_group_id}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>{l.virtual_device_name} · 本地发送 {l.local_send_audio === false ? '关' : '开'} · 本地接收 {l.local_receive_audio === false ? '关' : '开'}</Typography><Typography variant="body2" sx={{ mt: 2 }}>接收 {r.in_packets || 0} 包 · 发送 {r.out_packets || 0} 包 · 丢弃 {r.dropped_packets || 0} 包</Typography>{r.last_error && <Alert severity="warning" sx={{ mt: 2 }}>{r.last_error}</Alert>}</CardContent></Card>)}</Box>
  <Dialog open={inviteOpen} onClose={() => !busy && setInviteOpen(false)} fullWidth maxWidth="sm"><DialogTitle>生成中心互联邀请</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><Typography variant="body2" color="text.secondary">选择本地群组和互联权限，生成邀请 Token。</Typography><TextField select label="本地群组" value={invite.local_group_id || ''} onChange={e => setInvite({ ...invite, local_group_id: Number(e.target.value) })}>{groups.map(g => <MenuItem key={g.id} value={g.id}>{g.name}（{g.id}）</MenuItem>)}</TextField><TextField label="本地虚拟设备名称" value={invite.virtual_device_name} placeholder="Server-A" onChange={e => setInvite({ ...invite, virtual_device_name: e.target.value })} /><FormControlLabel control={<Switch checked={invite.send_audio} onChange={e => setInvite({ ...invite, send_audio: e.target.checked })} />} label="允许本地音频发送到对端" /><FormControlLabel control={<Switch checked={invite.receive_audio} onChange={e => setInvite({ ...invite, receive_audio: e.target.checked })} />} label="允许接收对端音频" /></Stack></DialogContent><DialogActions><Button onClick={() => setInviteOpen(false)}>取消</Button><Button variant="contained" disabled={busy || !invite.local_group_id} onClick={() => void submitInvite()}>生成</Button></DialogActions></Dialog>
  <Dialog open={importOpen} onClose={() => !busy && setImportOpen(false)} fullWidth maxWidth="sm"><DialogTitle>导入对端邀请</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="对端 Token" multiline minRows={2} value={incoming.invite_token} onChange={e => setIncoming({ ...incoming, invite_token: e.target.value.trim() })} /><TextField label="A 服务器地址" placeholder="https://a.example.com" helperText="填写对端主站地址。" value={incoming.remote_address} onChange={e => setIncoming({ ...incoming, remote_address: e.target.value.trim() })} /><TextField select label="本地群组" value={incoming.local_group_id || ''} onChange={e => setIncoming({ ...incoming, local_group_id: Number(e.target.value) })}>{groups.map(g => <MenuItem key={g.id} value={g.id}>{g.name}（{g.id}）</MenuItem>)}</TextField><FormControlLabel control={<Switch checked={incoming.send_audio} onChange={e => setIncoming({ ...incoming, send_audio: e.target.checked })} />} label="允许本地音频发送到对端" /><FormControlLabel control={<Switch checked={incoming.receive_audio} onChange={e => setIncoming({ ...incoming, receive_audio: e.target.checked })} />} label="允许接收对端音频" /></Stack></DialogContent><DialogActions><Button onClick={() => setImportOpen(false)}>取消</Button><Button variant="contained" disabled={busy || !incoming.invite_token || !incoming.remote_address || !incoming.local_group_id} onClick={() => void submitImport()}>连接</Button></DialogActions></Dialog>
  <Dialog open={!!generated} onClose={() => setGenerated('')} fullWidth maxWidth="sm"><DialogTitle>邀请 Token</DialogTitle><DialogContent><Alert severity="warning">Token 仅在生成后显示一次，请妥善保存。</Alert><TextField fullWidth multiline minRows={3} label="Token" value={generated} slotProps={{ input: { readOnly: true } }} sx={{ mt: 2 }} /></DialogContent><DialogActions><Button onClick={() => setGenerated('')}>我已保存</Button></DialogActions></Dialog>
 </Stack>
}
